security:
    
    factories:
      - "%kernel.root_dir%/../vendor/bundles/FOS/TwitterBundle/Resources/config/security_factories.xml"

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_twitter:
            id: fos_twitter.auth

    firewalls:
        
        public:
            pattern:   /.*
            anonymous: true
            fos_twitter: true
            logout: true
            
        secured:
            pattern:   /login_check
            fos_twitter: true

        # login:
        #     pattern:   /login/.*
        #     anonymous: true
        #     fos_twitter: true
        #     logout: true


    access_control:
        - { path: /.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }