security:
    
    factories:
      - "%kernel.root_dir%/../vendor/bundles/FOS/TwitterBundle/Resources/config/security_factories.xml"

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_twitter:
            id: fos_twitter.auth

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured:
            pattern:    ^/
            anonymous: true
            fos_twitter: true
            logout: ~
            provider: fos_twitter

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }
        # - { path: ^/, roles: IS_AUTHENTICATED_FULLY }