services:
  twitter.api:
    class: App\Bundle\WebBundle\Services\Twitter\ApiService
    arguments:
      twitter: @fos_twitter.api
      container: @service_container
  
  lomatwee.worker:
    class: App\Bundle\WebBundle\Services\LomaTweeWorkerService
    arguments:
      twitter: @twitter.api
      container: @service_container