services:
  lomatwee.worker:
    class: App\Bundle\WebBundle\Services\LomaTweeWorkerService
    arguments:
      twitter: @fos_twitter.api
      container: @service_container
      
  lomadee.api:
      class: App\Bundle\WebBundle\Services\Lomadee\ApiService
      arguments:
          container: @service_container
          appid: $lomadee_app_id
          development: $lomadee_use_sandbox